name = "flylist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# 1. 创建 KV 命名空间: wrangler kv namespace create FLYLIST_KV
# 2. 将下方 id 替换为创建后返回的 id
[[kv_namespaces]]
binding = "FLYLIST_KV"
id = "4f075d41b6e34deeb0fde7953bdcb820"
